import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, Button, Card, Input, Textarea } from '@/components/ui';
import { hygieneMethodCatalog } from '@/domain/hygiene/catalog';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { env } from '@/lib/env';

const auditTone = (status: string): 'success' | 'warning' | 'danger' => status === 'PASSED' ? 'success' : status === 'PASSED_WITH_WARNINGS' ? 'warning' : 'danger';
const measurementTone = (status: string): 'success' | 'warning' | 'danger' | 'neutral' => status === 'APPROVED' ? 'success' : status === 'INVALID' || status === 'REJECTED' ? 'danger' : status === 'REVIEW' ? 'warning' : 'neutral';

export default async function HygienePage({ params }: { params: Promise<{ id: string }> }) {
  if (!env.FEATURE_OCCUPATIONAL_HYGIENE) notFound();
  const { id } = await params;
  const { tenant } = await requireTenantPermission('hygiene.read');
  const project = await db.workProject.findFirst({
    where: { id, tenantId: tenant.id, serviceType: 'HIGIENE_OCUPACIONAL' },
    include: {
      company: { include: { establishments: { where: { active: true }, include: { sectors: { where: { active: true }, include: { ghes: { where: { active: true }, include: { functions: { where: { active: true } }, workstations: { where: { active: true } } } } } } } } } },
      hygieneProgram: { include: { samplingPlans: { include: { measurements: { include: { instrument: true, calibration: true }, orderBy: { measuredAt: 'desc' } } }, orderBy: { createdAt: 'desc' } }, audits: { orderBy: { createdAt: 'desc' }, take: 5 } } },
    },
  });
  if (!project) notFound();
  const instruments = env.FEATURE_INSTRUMENT_MANAGEMENT ? await db.measurementInstrument.findMany({ where: { tenantId: tenant.id, active: true }, include: { calibrations: { orderBy: { validUntil: 'desc' }, take: 1 }, events: { orderBy: { occurredAt: 'desc' }, take: 3 } }, orderBy: { code: 'asc' } }) : [];
  const program = project.hygieneProgram;
  if (!program) return <div><p className="text-sm font-semibold text-cyan-700">Higiene Ocupacional</p><h1 className="text-3xl font-bold">{project.title}</h1><p className="mt-1 text-slate-500">Inicialize o programa para planejar amostragens, medições, instrumentos e auditoria.</p><Card className="mt-6"><form action={`/api/hygiene/${id}/bootstrap`} method="post"><Button type="submit">Inicializar higiene ocupacional</Button></form></Card></div>;
  const measurements = program.samplingPlans.flatMap((plan) => plan.measurements);
  const latestAudit = program.audits[0];
  const ghes = project.company.establishments.flatMap((est) => est.sectors.flatMap((sector) => sector.ghes.map((ghe) => ({ id: ghe.id, label: `${est.name} · ${sector.name} · ${ghe.name}` }))));
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-cyan-700">Higiene Ocupacional</p><h1 className="text-3xl font-bold">{program.title}</h1><p className="mt-1 text-slate-500">{project.company.tradeName ?? project.company.legalName} · estratégia, campo, cálculo e rastreabilidade metrológica</p></div><div className="flex gap-2"><Link href={`/work-projects/${id}`} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Ver Trabalho SST</Link><form action={`/api/hygiene/${id}/audit`} method="post"><Button type="submit">Executar auditoria</Button></form></div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-5"><Card><p className="text-xs text-slate-500">Planos</p><p className="text-2xl font-bold">{program.samplingPlans.length}</p></Card><Card><p className="text-xs text-slate-500">Medições</p><p className="text-2xl font-bold">{measurements.length}</p></Card><Card><p className="text-xs text-slate-500">Aprovadas</p><p className="text-2xl font-bold">{measurements.filter((item) => item.status === 'APPROVED').length}</p></Card><Card><p className="text-xs text-slate-500">Instrumentos</p><p className="text-2xl font-bold">{instruments.length}</p></Card><Card><p className="text-xs text-slate-500">Auditoria</p><p className="text-2xl font-bold">{latestAudit?.score ?? '—'}</p>{latestAudit && <Badge tone={auditTone(latestAudit.status)}>{latestAudit.status}</Badge>}</Card></div>

    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-bold">Estratégia e plano de amostragem</h2><form action={`/api/hygiene/${id}/sampling-plans`} method="post" className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Código<Input name="code" className="mt-1" required /></label><label className="text-sm">Título<Input name="title" className="mt-1" required /></label></div><label className="text-sm">Agente<select name="agentCategory" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="NOISE">Ruído</option><option value="HEAT">Calor</option><option value="WHOLE_BODY_VIBRATION">Vibração de corpo inteiro</option><option value="HAND_ARM_VIBRATION">Vibração de mãos e braços</option><option value="ILLUMINANCE">Iluminamento</option><option value="CHEMICAL">Agente químico</option><option value="PARTICULATE">Material particulado</option><option value="BIOLOGICAL">Agente biológico</option><option value="OTHER">Outro</option></select></label><label className="text-sm">Estratégia<select name="strategy" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="PERSONAL">Pessoal</option><option value="AREA">Área</option><option value="TASK">Tarefa</option><option value="SCREENING">Triagem</option><option value="CONFIRMATORY">Confirmatória</option><option value="DIRECT_READING">Leitura direta</option><option value="INTEGRATED_SAMPLE">Amostra integrada</option></select></label><label className="text-sm">Objetivo<Textarea name="objective" className="mt-1" rows={3} required minLength={10} /></label><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">GHE<select name="gheId" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Sem vínculo</option>{ghes.map((ghe) => <option key={ghe.id} value={ghe.id}>{ghe.label}</option>)}</select></label><label className="text-sm">Mínimo de amostras<Input name="minimumSamples" type="number" min={1} defaultValue={1} className="mt-1" /></label></div><label className="text-sm">Método<select name="methodCode" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5">{hygieneMethodCatalog.map((method) => <option key={method.code} value={method.code}>{method.code} · {method.name}</option>)}</select></label><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Edição/versão<Input name="methodVersion" className="mt-1" /></label><label className="text-sm">Data planejada<Input name="scheduledAt" type="date" className="mt-1" /></label></div><label className="text-sm">Checklist de campo<Textarea name="fieldChecklist" className="mt-1" rows={3} placeholder="Um item por linha" /></label><Button type="submit">Salvar plano</Button></form></Card>

    <Card><h2 className="font-bold">Registrar medição ou amostra</h2><form action={`/api/hygiene/${id}/measurements`} method="post" className="mt-4 grid gap-3"><label className="text-sm">Plano<select name="samplingPlanId" required className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Selecione</option>{program.samplingPlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.code} · {plan.title}</option>)}</select></label><label className="text-sm">Instrumento<select name="instrumentId" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Sem instrumento</option>{instruments.map((instrument) => <option key={instrument.id} value={instrument.id}>{instrument.code} · {instrument.type} · {instrument.status}</option>)}</select></label><label className="text-sm">Método<select name="methodCode" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5">{hygieneMethodCatalog.map((method) => <option key={method.code} value={method.code}>{method.code} · {method.name}</option>)}</select></label><label className="text-sm">Entradas do motor (JSON)<Textarea name="engineInputs" className="mt-1 font-mono" rows={4} defaultValue={'{}'} /></label><div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Resultado manual<Input name="manualResult" type="number" step="any" className="mt-1" /></label><label className="text-sm">Unidade<Input name="unit" className="mt-1" /></label><label className="text-sm">Incerteza<Input name="uncertainty" type="number" step="any" className="mt-1" /></label></div><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Nível de ação<Input name="actionLevel" type="number" step="any" className="mt-1" /></label><label className="text-sm">Limite aplicável<Input name="toleranceLimit" type="number" step="any" className="mt-1" /></label></div><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Calibração de campo antes<Input name="fieldBefore" type="number" step="any" className="mt-1" /></label><label className="text-sm">Calibração de campo após<Input name="fieldAfter" type="number" step="any" className="mt-1" /></label></div><label className="text-sm">Dados brutos (JSON)<Textarea name="rawData" className="mt-1 font-mono" rows={3} defaultValue={'{}'} /></label><Button type="submit">Registrar medição</Button></form></Card></div>

    {env.FEATURE_INSTRUMENT_MANAGEMENT && <Card className="mt-6"><h2 className="font-bold">Instrumentos e calibrações</h2><div className="mt-4 grid gap-6 xl:grid-cols-2"><form action={`/api/hygiene/${id}/instruments`} method="post" className="grid gap-3"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Código<Input name="code" className="mt-1" required /></label><label className="text-sm">Tipo<select name="type" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="DOSIMETER">Dosímetro</option><option value="SOUND_LEVEL_METER">Decibelímetro</option><option value="ACOUSTIC_CALIBRATOR">Calibrador acústico</option><option value="HEAT_STRESS_METER">Medidor de estresse térmico</option><option value="VIBRATION_METER">Medidor de vibração</option><option value="SAMPLING_PUMP">Bomba de amostragem</option><option value="LUX_METER">Luxímetro</option><option value="OTHER">Outro</option></select></label></div><div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Fabricante<Input name="manufacturer" className="mt-1" /></label><label className="text-sm">Modelo<Input name="model" className="mt-1" /></label><label className="text-sm">Série<Input name="serialNumber" className="mt-1" /></label></div><label className="text-sm">Localização<Input name="currentLocation" className="mt-1" /></label><Button type="submit">Cadastrar instrumento</Button></form><div className="divide-y">{instruments.map((instrument) => <div key={instrument.id} className="py-3"><div className="flex items-center justify-between"><div><p className="font-medium">{instrument.code} · {instrument.manufacturer} {instrument.model}</p><p className="text-xs text-slate-500">{instrument.type} · série {instrument.serialNumber ?? 'não informada'} · {instrument.currentLocation ?? 'sem localização'}</p></div><Badge tone={instrument.status === 'AVAILABLE' ? 'success' : instrument.status === 'BLOCKED' || instrument.status === 'RETIRED' ? 'danger' : 'warning'}>{instrument.status}</Badge></div><p className="mt-1 text-xs text-slate-600">Calibração: {instrument.calibrations[0] ? `${instrument.calibrations[0].certificateNumber} até ${instrument.calibrations[0].validUntil.toISOString().slice(0,10)}` : 'não cadastrada'}</p><details className="mt-2"><summary className="cursor-pointer text-xs font-semibold">Registrar calibração</summary><form action={`/api/hygiene/${id}/instruments/${instrument.id}/calibrations`} method="post" className="mt-2 grid gap-2 md:grid-cols-2"><Input name="certificateNumber" placeholder="Certificado" required /><Input name="laboratory" placeholder="Laboratório" required /><Input name="calibratedAt" type="date" required /><Input name="validUntil" type="date" required /><Button type="submit">Salvar calibração</Button></form></details></div>)}</div></div></Card>}

    <Card className="mt-6"><h2 className="font-bold">Planos, medições e revisão profissional</h2><div className="mt-4 space-y-4">{program.samplingPlans.map((plan) => <div key={plan.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">{plan.code} · {plan.title}</p><p className="text-xs text-slate-500">{plan.agentCategory} · {plan.strategy} · {plan.methodCode ?? 'método pendente'} {plan.methodVersion ?? ''}</p></div><Badge tone={plan.measurements.length >= plan.minimumSamples ? 'success' : 'warning'}>{plan.measurements.length}/{plan.minimumSamples} amostras</Badge></div><div className="mt-3 divide-y">{plan.measurements.map((measurement) => <div key={measurement.id} className="py-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm">{measurement.methodCode} · {measurement.result?.toString() ?? '—'} {measurement.unit ?? ''} · {measurement.interpretation}</p><Badge tone={measurementTone(measurement.status)}>{measurement.status}</Badge></div><p className="text-xs text-slate-500">Instrumento: {measurement.instrument?.code ?? 'não vinculado'} · certificado: {measurement.calibration?.certificateNumber ?? 'não vinculado'}</p>{!['APPROVED','REJECTED'].includes(measurement.status) && <form action={`/api/hygiene/${id}/measurements/${measurement.id}/review`} method="post" className="mt-2 flex gap-2"><Button name="decision" value="approve" type="submit" disabled={measurement.status === 'INVALID'}>Aprovar resultado</Button><Button name="decision" value="reject" variant="secondary" type="submit">Rejeitar</Button></form>}</div>)}</div></div>)}</div></Card>

    <Card className="mt-6"><h2 className="font-bold">Auditorias técnicas</h2><div className="mt-3 divide-y">{program.audits.map((audit) => <div key={audit.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-medium">{audit.createdAt.toISOString().slice(0,16).replace('T',' ')}</p><p className="text-xs text-slate-500">Pontuação {audit.score}</p></div><Badge tone={auditTone(audit.status)}>{audit.status}</Badge></div>)}</div></Card>
  </div>;
}
