import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, Button, Card, Input, Textarea } from '@/components/ui';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { env } from '@/lib/env';

const tone=(status:string):'success'|'warning'|'danger'|'neutral'=>['APPROVED','COMPLIANT','ACCEPTED','CLOSED','COMPLETED'].includes(status)?'success':['REJECTED','NON_COMPLIANT','BLOCKED','OVERDUE'].includes(status)?'danger':['PENDING','PARTIAL','OPEN','IN_PROGRESS','VALIDATED','QUEUED'].includes(status)?'warning':'neutral';

export default async function OperationsPage({params}:{params:Promise<{id:string}>}){
  if(!env.FEATURE_OPERATIONAL_SST)notFound(); const{id}=await params; const{tenant}=await requireTenantPermission('operations.read');
  const project=await db.workProject.findFirst({where:{id,tenantId:tenant.id,serviceType:'OPERACAO_SST'},include:{company:true}}); if(!project)notFound();
  const program=await db.operationalSstProgram.findUnique({where:{workProjectId:id}}); if(!program)return <div><p className="text-sm font-semibold text-teal-700">Operação SST 360</p><h1 className="text-3xl font-bold">{project.title}</h1><p className="mt-1 text-slate-500">Inicialize o programa integrado para EPI, acidentes, permissões, máquinas, químicos, emergências, CIPA, contratadas e conformidade.</p><Card className="mt-6"><form action={`/api/operations/${id}/bootstrap`} method="post"><Button type="submit">Inicializar Operação SST 360</Button></form></Card></div>;
  const [ppe,transactions,incidents,permits,machines,chemicals,emergency,cipa,contractors,obligations,audits,esocial]=await Promise.all([
    db.ppeCatalogItem.findMany({where:{tenantId:tenant.id,active:true,OR:[{companyId:project.companyId},{companyId:null}]},orderBy:{name:'asc'}}),
    db.ppeTransaction.findMany({where:{operationalProgramId:program.id},orderBy:{occurredAt:'desc'},take:20}),
    db.safetyIncidentRecord.findMany({where:{operationalProgramId:program.id},orderBy:{occurredAt:'desc'},take:20}),
    db.workPermit.findMany({where:{operationalProgramId:program.id},orderBy:{startsAt:'desc'},take:20}),
    db.machineAsset.findMany({where:{operationalProgramId:program.id},orderBy:{name:'asc'}}),
    db.chemicalProduct.findMany({where:{operationalProgramId:program.id,active:true},orderBy:{name:'asc'}}),
    db.emergencyPlan.findMany({where:{operationalProgramId:program.id},orderBy:{createdAt:'desc'}}),
    db.cipaCycle.findMany({where:{operationalProgramId:program.id},orderBy:{startAt:'desc'}}),
    db.contractorCompany.findMany({where:{operationalProgramId:program.id},orderBy:{legalName:'asc'}}),
    db.complianceObligation.findMany({where:{operationalProgramId:program.id},orderBy:[{dueAt:'asc'},{code:'asc'}]}),
    db.operationalAuditRun.findMany({where:{operationalProgramId:program.id},orderBy:{createdAt:'desc'},take:5}),
    db.esocialEventQueue.findMany({where:{tenantId:tenant.id,companyId:project.companyId},orderBy:{createdAt:'desc'},take:20}),
  ]);
  const workers=await db.occupationalWorker.findMany({where:{tenantId:tenant.id,companyId:project.companyId,status:'ACTIVE'},orderBy:{fullName:'asc'},take:500}); const latestAudit=audits[0];
  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-teal-700">Operação SST 360</p><h1 className="text-3xl font-bold">{program.title}</h1><p className="mt-1 text-slate-500">{project.company.tradeName??project.company.legalName} · operação, conformidade, portais e integrações</p></div><div className="flex gap-2"><Link href={`/work-projects/${id}`} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Ver Trabalho SST</Link><form action={`/api/operations/${id}/audit`} method="post"><Button type="submit">Executar auditoria</Button></form></div></div>
  <div className="mt-6 grid gap-4 md:grid-cols-4 xl:grid-cols-8"><Card><p className="text-xs text-slate-500">EPI</p><p className="text-2xl font-bold">{ppe.length}</p></Card><Card><p className="text-xs text-slate-500">Entregas</p><p className="text-2xl font-bold">{transactions.length}</p></Card><Card><p className="text-xs text-slate-500">Ocorrências</p><p className="text-2xl font-bold">{incidents.length}</p></Card><Card><p className="text-xs text-slate-500">PTs</p><p className="text-2xl font-bold">{permits.length}</p></Card><Card><p className="text-xs text-slate-500">Máquinas</p><p className="text-2xl font-bold">{machines.length}</p></Card><Card><p className="text-xs text-slate-500">Químicos</p><p className="text-2xl font-bold">{chemicals.length}</p></Card><Card><p className="text-xs text-slate-500">Contratadas</p><p className="text-2xl font-bold">{contractors.length}</p></Card><Card><p className="text-xs text-slate-500">Auditoria</p><p className="text-2xl font-bold">{latestAudit?.score??'—'}</p>{latestAudit&&<Badge tone={tone(latestAudit.status)}>{latestAudit.status}</Badge>}</Card></div>

  <Card className="mt-6"><h2 className="font-bold">Governança do programa</h2><form action={`/api/operations/${id}/program`} method="post" className="mt-4 grid gap-3"><label className="text-sm">Escopo<Textarea name="scope" defaultValue={program.scope??''} rows={3} className="mt-1" required minLength={15}/></label><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Responsável<Input name="responsibleUserId" defaultValue={program.responsibleUserId??''} className="mt-1"/></label><label className="text-sm">Próxima revisão<Input name="nextReviewAt" type="date" defaultValue={program.nextReviewAt?.toISOString().slice(0,10)??''} className="mt-1"/></label></div><Button type="submit">Salvar governança</Button></form></Card>

  <div className="mt-6 grid gap-6 xl:grid-cols-2">
  {env.FEATURE_EPI_EPC&&<Card><h2 className="font-bold">EPI, CA e entregas</h2><form action={`/api/operations/${id}/ppe/items`} method="post" className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-2"><Input name="code" placeholder="Código" required/><Input name="name" placeholder="EPI" required/></div><div className="grid gap-3 md:grid-cols-3"><Input name="category" placeholder="Categoria" required/><Input name="caNumber" placeholder="CA"/><Input name="caExpiresAt" type="date"/></div><div className="grid gap-3 md:grid-cols-2"><Input name="stockQuantity" type="number" min={0} defaultValue={0} placeholder="Estoque"/><Input name="minimumStock" type="number" min={0} defaultValue={0} placeholder="Mínimo"/></div><Button type="submit">Cadastrar EPI</Button></form><form action={`/api/operations/${id}/ppe/transactions`} method="post" className="mt-5 grid gap-3 border-t pt-4"><select name="workerId" required className="rounded-xl border px-3 py-2.5"><option value="">Trabalhador</option>{workers.map(w=><option key={w.id} value={w.id}>{w.fullName}</option>)}</select><select name="ppeItemId" required className="rounded-xl border px-3 py-2.5"><option value="">EPI</option>{ppe.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name} · estoque {item.stockQuantity}</option>)}</select><div className="grid gap-3 md:grid-cols-3"><select name="type" className="rounded-xl border px-3 py-2.5"><option value="ISSUE">Entrega</option><option value="RETURN">Devolução</option><option value="EXCHANGE">Troca</option><option value="LOSS">Perda</option><option value="DAMAGE">Dano</option></select><Input name="quantity" type="number" min={1} defaultValue={1}/><Input name="size" placeholder="Tamanho"/></div><div className="flex gap-4 text-sm"><label><input type="checkbox" name="trainingConfirmed"/> Orientação confirmada</label><label><input type="checkbox" name="fitConfirmed"/> Adequação confirmada</label></div><Button type="submit">Registrar movimentação</Button></form></Card>}

  {env.FEATURE_INCIDENTS_CAT&&<Card><h2 className="font-bold">Acidentes, incidentes e CAT</h2><form action={`/api/operations/${id}/incidents`} method="post" className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-2"><select name="kind" className="rounded-xl border px-3 py-2.5"><option value="ACCIDENT">Acidente</option><option value="OCCUPATIONAL_DISEASE">Doença ocupacional</option><option value="NEAR_MISS">Quase acidente</option><option value="UNSAFE_CONDITION">Condição insegura</option><option value="PROPERTY_DAMAGE">Dano material</option></select><select name="severity" className="rounded-xl border px-3 py-2.5"><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></div><Input name="title" placeholder="Título" required/><Textarea name="description" placeholder="Descrição detalhada" rows={3} required minLength={10}/><div className="grid gap-3 md:grid-cols-2"><Input name="occurredAt" type="datetime-local" required/><select name="workerId" className="rounded-xl border px-3 py-2.5"><option value="">Sem trabalhador identificado</option>{workers.map(w=><option key={w.id} value={w.id}>{w.fullName}</option>)}</select></div><div className="flex gap-4 text-sm"><label><input type="checkbox" name="lostTime"/> Afastamento</label><label><input type="checkbox" name="fatality"/> Fatalidade</label></div><Button type="submit">Registrar ocorrência</Button></form><div className="mt-4 divide-y">{incidents.map(item=><div key={item.id} className="py-2"><div className="flex justify-between"><p className="text-sm font-medium">{item.title}</p><Badge tone={tone(item.status)}>{item.status}</Badge></div><p className="text-xs text-slate-500">{item.kind} · {item.severity} · CAT {item.catRequired?'necessária':'não indicada'}</p></div>)}</div></Card>}

  {env.FEATURE_WORK_PERMITS&&<Card><h2 className="font-bold">Permissões de trabalho</h2><form action={`/api/operations/${id}/permits`} method="post" className="mt-4 grid gap-3"><select name="type" className="rounded-xl border px-3 py-2.5"><option value="WORK_AT_HEIGHT">Trabalho em altura</option><option value="CONFINED_SPACE">Espaço confinado</option><option value="ELECTRICAL">Eletricidade</option><option value="HOT_WORK">Trabalho a quente</option><option value="EXCAVATION">Escavação</option><option value="LOCKOUT_TAGOUT">Bloqueio e etiquetagem</option></select><Input name="title" placeholder="Título" required/><Input name="location" placeholder="Local" required/><div className="grid gap-3 md:grid-cols-2"><Input name="startsAt" type="datetime-local" required/><Input name="endsAt" type="datetime-local" required/></div><Textarea name="controls" rows={3} placeholder="Controles, um por linha"/><Textarea name="workers" rows={3} placeholder="Equipe, um por linha"/><Textarea name="checklist" rows={3} placeholder="Checklist concluído, um item por linha"/><Input name="approverUserId" placeholder="ID do aprovador"/><label className="text-sm"><input type="checkbox" name="authorize"/> Autorizar agora</label><Button type="submit">Salvar permissão</Button></form><div className="mt-4 divide-y">{permits.map(item=><div key={item.id} className="flex justify-between py-2"><div><p className="text-sm font-medium">{item.title}</p><p className="text-xs text-slate-500">{item.type} · {item.location}</p></div><Badge tone={tone(item.status)}>{item.status}</Badge></div>)}</div></Card>}

  {env.FEATURE_MACHINES_NR12&&<Card><h2 className="font-bold">Máquinas e NR-12</h2><form action={`/api/operations/${id}/machines`} method="post" className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-2"><Input name="code" placeholder="Código" required/><Input name="name" placeholder="Máquina" required/></div><div className="grid gap-3 md:grid-cols-2"><Input name="manufacturer" placeholder="Fabricante"/><Input name="model" placeholder="Modelo"/></div><select name="riskLevel" className="rounded-xl border px-3 py-2.5"><option value="">Risco não classificado</option><option value="LOW">Baixo</option><option value="MODERATE">Moderado</option><option value="HIGH">Alto</option><option value="CRITICAL">Crítico</option></select><Textarea name="protections" rows={2} placeholder="Proteções, uma por linha"/><Input name="nextInspectionAt" type="date"/><Button type="submit">Cadastrar máquina</Button></form><div className="mt-4 divide-y">{machines.map(item=><div key={item.id} className="flex justify-between py-2"><div><p className="text-sm font-medium">{item.code} · {item.name}</p><p className="text-xs text-slate-500">{item.manufacturer} {item.model} · inspeção {item.nextInspectionAt?.toISOString().slice(0,10)??'não definida'}</p></div><Badge tone={tone(item.status)}>{item.status}</Badge></div>)}</div></Card>}

  {env.FEATURE_CHEMICALS&&<Card><h2 className="font-bold">Produtos químicos e FDS</h2><form action={`/api/operations/${id}/chemicals`} method="post" className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-2"><Input name="productCode" placeholder="Código" required/><Input name="name" placeholder="Produto" required/></div><Input name="manufacturer" placeholder="Fabricante"/><Input name="sdsRevision" placeholder="Revisão da FDS"/><Textarea name="hazardClasses" rows={2} placeholder="Classes de perigo, uma por linha"/><Textarea name="storageRules" rows={2} placeholder="Regras de armazenamento"/><Textarea name="incompatibilities" rows={2} placeholder="Incompatibilidades"/><Button type="submit">Cadastrar produto</Button></form><div className="mt-4 divide-y">{chemicals.map(item=><div key={item.id} className="py-2"><p className="text-sm font-medium">{item.productCode} · {item.name}</p><p className="text-xs text-slate-500">FDS {item.sdsFileId?'vinculada':'pendente'} · revisão {item.sdsRevision??'não informada'}</p></div>)}</div></Card>}

  {env.FEATURE_EMERGENCY_CIPA&&<Card><h2 className="font-bold">Emergências e CIPA</h2><form action={`/api/operations/${id}/emergency`} method="post" className="mt-4 grid gap-3"><Input name="title" placeholder="Plano de emergência" required/><Textarea name="scenarios" rows={3} placeholder="Cenários, um por linha"/><Textarea name="responseTeams" rows={3} placeholder="Equipes, uma por linha"/><Input name="nextDrillAt" type="date"/><Input name="approvedById" placeholder="ID do aprovador"/><label className="text-sm"><input type="checkbox" name="approve"/> Aprovar plano</label><Button type="submit">Salvar plano</Button></form><form action={`/api/operations/${id}/cipa`} method="post" className="mt-5 grid gap-3 border-t pt-4"><Input name="title" placeholder="Ciclo da CIPA" required/><div className="grid gap-3 md:grid-cols-2"><Input name="startAt" type="date" required/><Input name="endAt" type="date" required/></div><Textarea name="members" rows={2} placeholder="Membros, um por linha"/><Textarea name="harassmentActions" rows={2} placeholder="Ações de prevenção ao assédio"/><Button type="submit">Criar ciclo CIPA</Button></form><p className="mt-4 text-sm">Planos: {emergency.length} · ciclos CIPA: {cipa.length}</p></Card>}

  {env.FEATURE_CONTRACTORS&&<Card><h2 className="font-bold">Contratadas e liberação de acesso</h2><form action={`/api/operations/${id}/contractors`} method="post" className="mt-4 grid gap-3"><Input name="legalName" placeholder="Razão social" required/><Input name="taxId" placeholder="CNPJ"/><div className="grid gap-3 md:grid-cols-2"><Input name="contractStart" type="date"/><Input name="contractEnd" type="date"/></div><Input name="responsibleName" placeholder="Responsável"/><Textarea name="workers" rows={2} placeholder="Trabalhadores liberados, um por linha"/><Textarea name="documents" rows={2} placeholder="Documentos válidos, um por linha"/><label className="text-sm"><input type="checkbox" name="integrationCompleted"/> Integração concluída</label><Button type="submit">Cadastrar contratada</Button></form><div className="mt-4 divide-y">{contractors.map(item=><div key={item.id} className="flex justify-between py-2"><div><p className="text-sm font-medium">{item.legalName}</p><p className="text-xs text-slate-500">Conformidade {item.complianceScore}%</p></div><Badge tone={tone(item.status)}>{item.status}</Badge></div>)}</div></Card>}
  </div>

  <Card className="mt-6"><h2 className="font-bold">Matriz legal, eSocial e auditoria</h2><div className="mt-4 grid gap-6 xl:grid-cols-2"><form action={`/api/operations/${id}/obligations`} method="post" className="grid gap-3"><div className="grid gap-3 md:grid-cols-2"><Input name="code" placeholder="Código" required/><Input name="title" placeholder="Obrigação" required/></div><Input name="source" placeholder="Fonte normativa ou contratual" required/><Textarea name="applicability" rows={2} placeholder="Aplicabilidade" required/><div className="grid gap-3 md:grid-cols-2"><Input name="frequency" placeholder="Periodicidade"/><Input name="dueAt" type="date"/></div><Button type="submit">Salvar obrigação</Button></form><div><p className="text-sm font-semibold">Eventos SST do eSocial</p><div className="mt-2 divide-y">{esocial.map(item=><div key={item.id} className="flex justify-between py-2"><div><p className="text-sm">{item.eventType} · {item.relatedEntityType}</p><p className="text-xs text-slate-500">{item.environment} · leiaute {item.layoutVersion}</p></div><Badge tone={tone(item.status)}>{item.status}</Badge></div>)}</div><p className="mt-4 text-sm font-semibold">Obrigações</p><div className="mt-2 divide-y">{obligations.slice(0,10).map(item=><div key={item.id} className="flex justify-between py-2"><div><p className="text-sm">{item.code} · {item.title}</p><p className="text-xs text-slate-500">{item.source} · {item.dueAt?.toISOString().slice(0,10)??'sem prazo'}</p></div><Badge tone={tone(item.status)}>{item.status}</Badge></div>)}</div></div></div></Card>
  </div>;
}
