import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, Button, Card, Input, Textarea } from '@/components/ui';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { env } from '@/lib/env';
import { hasTenantPermission } from '@/lib/rbac';
import { occupationalExamTypeLabels } from '@/domain/pcmso/catalog';

const tone = (status: string): 'success' | 'warning' | 'danger' | 'neutral' => {
  if (['APPROVED', 'ISSUED', 'COMPLETED', 'VALIDATED', 'READY', 'ACCEPTED', 'PASSED'].includes(status)) return 'success';
  if (['FAILED', 'REJECTED', 'UNFIT', 'CANCELLED'].includes(status)) return 'danger';
  if (['REVIEW', 'OVERDUE', 'PASSED_WITH_WARNINGS', 'FIT_WITH_RESTRICTIONS'].includes(status)) return 'warning';
  return 'neutral';
};
const list = (value: unknown) => Array.isArray(value) ? value.map(String) : [];
const findingMessages = (value: unknown) => Array.isArray(value) ? value.map((item) => {
  if (item && typeof item === 'object' && 'message' in item) return String((item as { message?: unknown }).message ?? '');
  return String(item);
}).filter(Boolean) : [];
const dateInput = (value = new Date()) => value.toISOString().slice(0, 10);

export default async function PcmsoPage({ params }: { params: Promise<{ id: string }> }) {
  if (!env.FEATURE_PCMSO) notFound();
  const { id } = await params;
  const context = await requireTenantPermission('medical.program.read');
  const { tenant, membership, user } = context;
  const canManage = hasTenantPermission(membership.role, 'medical.program.manage', membership.permissions);
  const canManageWorkers = hasTenantPermission(membership.role, 'medical.worker.manage', membership.permissions);
  const canReadClinical = env.FEATURE_MEDICAL_AREA && hasTenantPermission(membership.role, 'medical.clinical.read', membership.permissions);
  const canWriteClinical = env.FEATURE_MEDICAL_AREA && hasTenantPermission(membership.role, 'medical.clinical.write', membership.permissions);
  const canIssueAso = env.FEATURE_MEDICAL_AREA && hasTenantPermission(membership.role, 'medical.aso.issue', membership.permissions);
  const canPrepareEsocial = env.FEATURE_ESOCIAL_S2220 && hasTenantPermission(membership.role, 'esocial.prepare', membership.permissions);

  const project = await db.workProject.findFirst({
    where: { id, tenantId: tenant.id, serviceType: 'PCMSO' },
    include: {
      company: {
        include: {
          establishments: { where: { active: true }, include: { sectors: { where: { active: true }, include: { ghes: { where: { active: true }, include: { functions: { where: { active: true } } } } } } } },
        },
      },
      pcmsoProgram: {
        include: {
          responsiblePhysician: true,
          examRequirements: { include: { examCatalog: true, ghe: { select: { name: true } }, jobFunction: { select: { name: true } }, pgrRiskAssessment: { select: { code: true, hazard: true } } }, orderBy: { createdAt: 'desc' } },
          calls: { include: { worker: { select: { fullName: true, registration: true } }, provider: { select: { name: true } } }, orderBy: { dueAt: 'asc' }, take: 50 },
          analyticalReports: { orderBy: { periodEnd: 'desc' }, take: 5 },
          audits: { orderBy: { createdAt: 'desc' }, take: 5 },
          asos: { include: { worker: { select: { fullName: true, registration: true } }, issuingPhysician: { select: { name: true, councilNumber: true, councilState: true } }, exams: { include: { examCatalog: { select: { name: true } } } }, esocialDrafts: { orderBy: { revision: 'desc' }, take: 1 } }, orderBy: { asoDate: 'desc' }, take: canReadClinical ? 30 : 0 },
          _count: { select: { examRequirements: true, calls: true, asos: true, analyticalReports: true } },
        },
      },
    },
  });
  if (!project) notFound();
  const [providers, professionals, catalog, workers, pgrRisks] = await Promise.all([
    db.medicalProvider.findMany({ where: { tenantId: tenant.id, active: true }, orderBy: { name: 'asc' } }),
    db.medicalProfessional.findMany({ where: { tenantId: tenant.id, active: true }, select: { id: true, name: true, role: true, councilType: true, councilNumber: true, councilState: true, providerId: true }, orderBy: { name: 'asc' } }),
    db.pcmsoExamCatalog.findMany({ where: { tenantId: tenant.id, active: true }, orderBy: [{ kind: 'asc' }, { name: 'asc' }] }),
    db.occupationalWorker.findMany({ where: { tenantId: tenant.id, companyId: project.companyId, status: { not: 'ARCHIVED' } }, include: { ghe: { select: { name: true } }, jobFunction: { select: { name: true } } }, orderBy: { fullName: 'asc' }, take: 500 }),
    db.pgrRiskAssessment.findMany({ where: { pgrProgram: { companyId: project.companyId, tenantId: tenant.id } }, select: { id: true, code: true, hazard: true, gheId: true }, orderBy: { code: 'asc' }, take: 300 }),
  ]);
  const structure = project.company.establishments.flatMap((establishment) => establishment.sectors.flatMap((sector) => sector.ghes.map((ghe) => ({ establishment, sector, ghe }))));
  const functions = structure.flatMap(({ establishment, sector, ghe }) => ghe.functions.map((jobFunction) => ({ ...jobFunction, gheId: ghe.id, label: `${establishment.name} · ${sector.name} · ${ghe.name} · ${jobFunction.name}` })));
  const program = project.pcmsoProgram;

  if (!program) return <div><p className="text-sm font-semibold text-emerald-700">PCMSO</p><h1 className="text-3xl font-bold">{project.title}</h1><p className="mt-1 text-slate-500">Inicialize o programa para integrar riscos, trabalhadores, matriz de exames, ASO, relatório analítico e S-2220.</p><Card className="mt-6"><form action={`/api/pcmso/${id}/bootstrap`} method="post"><Button type="submit" disabled={!canManage}>Inicializar PCMSO</Button></form></Card></div>;

  const latestAudit = program.audits[0];
  const overdueCalls = program.calls.filter((call) => ['DRAFT', 'SCHEDULED', 'NOTIFIED', 'CONFIRMED'].includes(call.status) && call.dueAt < new Date()).length;
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-emerald-700">PCMSO e Saúde Ocupacional</p><h1 className="text-3xl font-bold">{program.title}</h1><p className="mt-1 text-slate-500">{project.company.tradeName ?? project.company.legalName} · próxima revisão {program.nextReviewAt?.toLocaleDateString('pt-BR') ?? 'não definida'}</p></div><div className="flex flex-wrap gap-2"><Link href={`/work-projects/${id}`} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Ver Trabalho SST</Link>{canManage && <form action={`/api/pcmso/${id}/audit`} method="post"><Button type="submit">Executar auditoria</Button></form>}</div></div>

    <div className="mt-6 grid gap-4 md:grid-cols-6"><Card><p className="text-xs text-slate-500">Trabalhadores</p><p className="mt-1 text-2xl font-bold">{workers.filter((item) => item.status === 'ACTIVE').length}</p></Card><Card><p className="text-xs text-slate-500">Matriz</p><p className="mt-1 text-2xl font-bold">{program._count.examRequirements}</p></Card><Card><p className="text-xs text-slate-500">Convocações</p><p className="mt-1 text-2xl font-bold">{program._count.calls}</p><p className="text-xs text-red-600">{overdueCalls} vencidas</p></Card><Card><p className="text-xs text-slate-500">ASOs</p><p className="mt-1 text-2xl font-bold">{program._count.asos}</p></Card><Card><p className="text-xs text-slate-500">Relatórios</p><p className="mt-1 text-2xl font-bold">{program._count.analyticalReports}</p></Card><Card><p className="text-xs text-slate-500">Auditoria</p><p className="mt-1 text-2xl font-bold">{latestAudit?.score ?? '—'}</p>{latestAudit && <Badge tone={tone(latestAudit.status)}>{latestAudit.status}</Badge>}</Card></div>

    {!canReadClinical && <Card className="mt-6 border-amber-200 bg-amber-50"><h2 className="font-bold text-amber-900">Área médica protegida</h2><p className="mt-1 text-sm text-amber-800">Este perfil visualiza o programa, vencimentos e indicadores agregados, mas não acessa resultados clínicos, restrições ou detalhes individuais do ASO.</p></Card>}

    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <Card><h2 className="font-bold">Médico responsável e rede credenciada</h2><p className="mt-1 text-sm text-slate-500">Cadastre clínicas e profissionais. O responsável pelo PCMSO precisa do perfil médico adequado.</p>{canManage && <><form action={`/api/pcmso/${id}/providers`} method="post" className="mt-4 grid gap-3 md:grid-cols-2"><Input name="name" required placeholder="Nome da clínica ou laboratório" /><select name="kind" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="CLINIC">Clínica</option><option value="LABORATORY">Laboratório</option><option value="INTERNAL_SERVICE">Serviço interno</option><option value="PARTNER">Parceiro</option><option value="OTHER">Outro</option></select><Input name="cnpj" placeholder="CNPJ" /><Input name="email" type="email" placeholder="E-mail" /><Button type="submit" className="md:col-span-2">Cadastrar prestador</Button></form><form action={`/api/pcmso/${id}/professionals`} method="post" className="mt-5 grid gap-3 md:grid-cols-2"><Input name="name" required placeholder="Nome do profissional" /><select name="role" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="RESPONSIBLE_PHYSICIAN">Médico responsável</option><option value="EXAMINING_PHYSICIAN">Médico examinador</option><option value="OCCUPATIONAL_NURSE">Enfermagem ocupacional</option><option value="MEDICAL_ASSISTANT">Assistente médico</option></select><Input name="cpf" placeholder="CPF — armazenado criptografado" /><Input name="councilNumber" required placeholder="Número do CRM/registro" /><Input name="councilState" required maxLength={2} placeholder="UF" /><select name="providerId" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Sem prestador</option>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select><Button type="submit" className="md:col-span-2">Cadastrar profissional</Button></form></>}
        <div className="mt-4 divide-y">{professionals.map((professional) => <div key={professional.id} className="flex items-center justify-between gap-3 py-2 text-sm"><span>{professional.name}<br/><small className="text-slate-500">{professional.councilType} {professional.councilNumber}/{professional.councilState}</small></span><Badge>{professional.role}</Badge></div>)}{!professionals.length && <p className="py-3 text-sm text-slate-500">Nenhum profissional cadastrado.</p>}</div>
        {canManage && <form action={`/api/pcmso/${id}/responsible`} method="post" className="mt-4 flex gap-2"><select name="physicianId" required className="min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Selecione o responsável</option>{professionals.filter((item) => item.role === 'RESPONSIBLE_PHYSICIAN').map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Button type="submit">Definir</Button></form>}
        {program.responsiblePhysician && <p className="mt-3 text-sm text-emerald-700">Responsável atual: <strong>{program.responsiblePhysician.name}</strong></p>}
      </Card>

      <Card><h2 className="font-bold">Cadastro ocupacional</h2><p className="mt-1 text-sm text-slate-500">CPF é criptografado; a área geral recebe somente dados ocupacionais necessários.</p>{canManageWorkers && <form action={`/api/pcmso/${id}/workers`} method="post" className="mt-4 grid gap-3 md:grid-cols-2"><Input name="fullName" required placeholder="Nome do trabalhador" /><Input name="registration" placeholder="Matrícula" /><Input name="cpf" placeholder="CPF" /><Input name="categoryCode" maxLength={3} placeholder="Categoria eSocial" /><Input name="admissionDate" type="date" /><select name="jobFunctionId" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Sem função vinculada</option>{functions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><Button type="submit" className="md:col-span-2">Cadastrar trabalhador</Button></form>}
        <div className="mt-4 max-h-80 overflow-auto divide-y">{workers.map((worker) => <div key={worker.id} className="flex justify-between gap-3 py-2 text-sm"><div><p className="font-medium">{worker.fullName}</p><p className="text-xs text-slate-500">{worker.registration ?? 'sem matrícula'} · {worker.jobFunction?.name ?? worker.ghe?.name ?? 'sem alocação'}</p></div><Badge tone={worker.status === 'ACTIVE' ? 'success' : 'neutral'}>{worker.status}</Badge></div>)}{!workers.length && <p className="py-3 text-sm text-slate-500">Nenhum trabalhador cadastrado.</p>}</div>
      </Card>
    </div>

    <Card className="mt-6"><h2 className="font-bold">Matriz de avaliações clínicas e exames</h2><p className="mt-1 text-sm text-slate-500">A definição final pertence ao médico responsável e pode ser vinculada a GHE, função e risco do PGR.</p>{canManage && <div className="mt-4 grid gap-6 xl:grid-cols-2"><form action={`/api/pcmso/${id}/exam-catalog`} method="post" className="grid gap-3 md:grid-cols-2"><Input name="code" required placeholder="Código interno" /><Input name="name" required placeholder="Nome do exame" /><select name="kind" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="CLINICAL">Avaliação clínica</option><option value="COMPLEMENTARY">Exame complementar</option></select><Input name="esocialProcedureCode" placeholder="Código do procedimento eSocial" /><Textarea name="description" className="md:col-span-2" placeholder="Descrição" /><Button type="submit" className="md:col-span-2">Salvar no catálogo</Button></form><form action={`/api/pcmso/${id}/matrix`} method="post" className="grid gap-3 md:grid-cols-2"><select name="examCatalogId" required className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Selecione o exame</option>{catalog.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="jobFunctionId" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Todas as funções</option>{functions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><select name="pgrRiskAssessmentId" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Sem risco específico</option>{pgrRisks.map((risk) => <option key={risk.id} value={risk.id}>{risk.code} · {risk.hazard}</option>)}</select><Input name="periodicityMonths" type="number" min={1} max={240} defaultValue={12} placeholder="Periodicidade em meses" /><fieldset className="md:col-span-2 grid grid-cols-2 gap-2 text-sm">{Object.entries(occupationalExamTypeLabels).map(([value, label]) => <label key={value} className="flex gap-2"><input type="checkbox" name="examTypes" value={value} defaultChecked={value === 'PERIODIC'} />{label}</label>)}</fieldset><Textarea name="medicalProtocol" className="md:col-span-2" placeholder="Protocolo ou critério médico" /><Button type="submit" className="md:col-span-2">Adicionar regra à matriz</Button></form></div>}
      <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="py-2 pr-3">Exame</th><th className="pr-3">Abrangência</th><th className="pr-3">Tipos</th><th>Periodicidade</th></tr></thead><tbody>{program.examRequirements.map((item) => <tr key={item.id} className="border-b"><td className="py-3 pr-3 font-medium">{item.examCatalog.name}</td><td className="pr-3">{item.jobFunction?.name ?? item.ghe?.name ?? 'Geral'}{item.pgrRiskAssessment ? <small className="block text-slate-500">{item.pgrRiskAssessment.code} · {item.pgrRiskAssessment.hazard}</small> : null}</td><td className="pr-3">{list(item.occupationalExamTypes).map((type) => occupationalExamTypeLabels[type] ?? type).join(', ')}</td><td>{item.periodicityMonths ? `${item.periodicityMonths} meses` : 'por evento'}</td></tr>)}{!program.examRequirements.length && <tr><td colSpan={4} className="py-4 text-slate-500">Matriz ainda não configurada.</td></tr>}</tbody></table></div>
    </Card>

    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold">Convocações e vencimentos</h2><p className="text-sm text-slate-500">Geração idempotente a partir da matriz e do último ASO.</p></div>{canManage && <form action={`/api/pcmso/${id}/callups`} method="post"><Button type="submit" variant="secondary">Gerar periódicos</Button></form>}</div><div className="mt-4 divide-y">{program.calls.map((call) => <div key={call.id} className="flex justify-between gap-3 py-3 text-sm"><div><p className="font-medium">{call.worker.fullName}</p><p className="text-xs text-slate-500">{occupationalExamTypeLabels[call.examType]} · vence {call.dueAt.toLocaleDateString('pt-BR')} · {call.provider?.name ?? 'prestador não definido'}</p></div><Badge tone={call.dueAt < new Date() && openCallStatusesForUi.includes(call.status) ? 'danger' : tone(call.status)}>{call.status}</Badge></div>)}{!program.calls.length && <p className="py-3 text-sm text-slate-500">Nenhuma convocação gerada.</p>}</div></Card>

      <Card><h2 className="font-bold">Relatório analítico e auditoria</h2><p className="mt-1 text-sm text-slate-500">Indicadores exclusivamente agregados, sem diagnóstico ou exposição individual.</p>{canManage && <form action={`/api/pcmso/${id}/analytical-report`} method="post" className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm">Início<Input className="mt-1" name="periodStart" type="date" required defaultValue={`${new Date().getUTCFullYear()}-01-01`} /></label><label className="text-sm">Fim<Input className="mt-1" name="periodEnd" type="date" required defaultValue={dateInput()} /></label><Button type="submit" className="md:col-span-2">Gerar relatório analítico</Button></form>}<div className="mt-4 divide-y">{program.analyticalReports.map((report) => <div key={report.id} className="flex justify-between gap-3 py-3 text-sm"><div><p className="font-medium">{report.periodStart.toLocaleDateString('pt-BR')} a {report.periodEnd.toLocaleDateString('pt-BR')}</p><p className="text-xs text-slate-500">{report.populationCount} trabalhadores · {report.examCount} exames · {report.abnormalExamCount} resultados alterados agregados</p></div><Badge tone={tone(report.status)}>{report.status}</Badge></div>)}{!program.analyticalReports.length && <p className="py-3 text-sm text-slate-500">Nenhum relatório gerado.</p>}</div>{latestAudit && <div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><strong>Última auditoria: {latestAudit.score}/100</strong><ul className="mt-2 list-disc pl-5 text-xs text-slate-600">{findingMessages(latestAudit.findings).slice(0, 6).map((item, index) => <li key={index}>{item}</li>)}</ul></div>}</Card></div>

    {canWriteClinical && <Card className="mt-6"><h2 className="font-bold">Emitir ASO</h2><p className="mt-1 text-sm text-slate-500">A emissão registra acesso médico, criptografa observações e não permite conclusão pendente.</p><form action={`/api/pcmso/${id}/asos`} method="post" className="mt-4 grid gap-3 lg:grid-cols-4"><select name="workerId" required className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Trabalhador</option>{workers.filter((item) => item.status === 'ACTIVE').map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select><select name="issuingPhysicianId" required className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Médico emitente</option>{professionals.filter((item) => ['RESPONSIBLE_PHYSICIAN', 'EXAMINING_PHYSICIAN'].includes(item.role)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="examType" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5">{Object.entries(occupationalExamTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Input name="asoDate" type="date" required defaultValue={dateInput()} /><select name="fitnessResult" required className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="FIT">Apto</option><option value="FIT_WITH_RESTRICTIONS">Apto com restrições</option><option value="UNFIT">Inapto</option></select><select name="examCatalogId" required className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Avaliação/exame realizado</option>{catalog.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input name="examPerformedAt" type="date" required defaultValue={dateInput()} /><select name="examResultStatus" className="rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="COMPLETED">Concluído</option><option value="ALTERED">Alterado</option><option value="PENDING">Pendente</option><option value="NOT_APPLICABLE">Não aplicável</option></select><Textarea name="restrictions" className="lg:col-span-2" placeholder="Restrições — campo médico criptografado" /><Textarea name="physicianNotes" className="lg:col-span-2" placeholder="Observações clínicas — campo médico criptografado" /><Button type="submit" disabled={!canIssueAso} className="lg:col-span-4">Emitir ASO</Button></form>
      {canReadClinical && <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="py-2 pr-3">Data</th><th className="pr-3">Trabalhador</th><th className="pr-3">Tipo</th><th className="pr-3">Aptidão</th><th>eSocial</th></tr></thead><tbody>{program.asos.map((aso) => <tr key={aso.id} className="border-b"><td className="py-3 pr-3">{aso.asoDate.toLocaleDateString('pt-BR')}</td><td className="pr-3">{aso.worker.fullName}<small className="block text-slate-500">{aso.issuingPhysician.name}</small></td><td className="pr-3">{occupationalExamTypeLabels[aso.examType]}</td><td className="pr-3"><Badge tone={tone(aso.fitnessResult)}>{aso.fitnessResult}</Badge></td><td>{aso.esocialDrafts[0] ? <Badge tone={tone(aso.esocialDrafts[0].status)}>{aso.esocialDrafts[0].status} r{aso.esocialDrafts[0].revision}</Badge> : canPrepareEsocial ? <form action={`/api/pcmso/${id}/esocial/${aso.id}`} method="post"><Button type="submit" variant="outline" className="px-3 py-1.5 text-xs">Preparar S-2220</Button></form> : 'não preparado'}</td></tr>)}{!program.asos.length && <tr><td colSpan={5} className="py-4 text-slate-500">Nenhum ASO emitido.</td></tr>}</tbody></table></div>}
    </Card>}

    <p className="mt-6 text-xs text-slate-500">Usuário atual: {user.name}. Dados clínicos são protegidos por permissão específica, criptografia de campos sensíveis e registro de acesso.</p>
  </div>;
}

const openCallStatusesForUi = ['DRAFT', 'SCHEDULED', 'NOTIFIED', 'CONFIRMED'];
