import Link from 'next/link';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { StatCard } from '@/components/stat-card';
import { Card, Badge } from '@/components/ui';
import { hasTenantPermission } from '@/lib/rbac';
import { formatDate } from '@/lib/utils';
import { env } from '@/lib/env';

export default async function Dashboard() {
  const { tenant, membership } = await requireTenantPermission('company.read');
  const canCreate = hasTenantPermission(membership.role, 'company.write', membership.permissions);
  const canManageWorks = hasTenantPermission(membership.role, 'work.manage', membership.permissions);
  const canMessage = hasTenantPermission(membership.role, 'message.manage', membership.permissions);
  const canInspect = hasTenantPermission(membership.role, 'inspection.manage', membership.permissions);
  const now = new Date();
  const inThirtyDays = new Date(now.getTime() + 30 * 86400000);
  const [companies, campaigns, documents, actions, servicesOverdue, servicesRenewing, messages, activeProjects, fieldVisits] = await Promise.all([
    db.company.count({ where: { tenantId: tenant.id, status: 'ACTIVE' } }),
    db.campaign.count({ where: { company: { tenantId: tenant.id }, status: 'ACTIVE' } }),
    db.document.count({ where: { company: { tenantId: tenant.id }, status: { in: ['REVIEW', 'WAITING_SIGNATURE', 'PREVIEW'] } } }),
    db.actionItem.count({ where: { actionPlan: { company: { tenantId: tenant.id } }, status: { in: ['NOT_STARTED', 'IN_PROGRESS', 'OVERDUE'] } } }),
    db.serviceContract.findMany({ where: { company: { tenantId: tenant.id }, active: true, dueAt: { lt: now }, status: { notIn: ['DELIVERED', 'COMPLETED', 'CANCELLED'] } }, include: { company: true }, orderBy: { dueAt: 'asc' }, take: 8 }),
    db.serviceContract.findMany({ where: { company: { tenantId: tenant.id }, active: true, renewalAt: { gte: now, lte: inThirtyDays }, status: { notIn: ['CANCELLED', 'EXPIRED'] } }, include: { company: true }, orderBy: { renewalAt: 'asc' }, take: 8 }),
    canMessage ? db.conversation.findMany({ where: { tenantId: tenant.id, status: { notIn: ['ARCHIVED', 'RESOLVED'] } }, include: { company: true }, orderBy: { lastMessageAt: 'desc' }, take: 5 }) : Promise.resolve([]),
    env.FEATURE_V10_WORKS && canManageWorks ? db.workProject.findMany({ where: { tenantId: tenant.id, status: { in: ['ACTIVE', 'WAITING_INPUT', 'WAITING_APPROVAL', 'IN_REVIEW'] } }, include: { company: { select: { legalName: true, tradeName: true } } }, orderBy: { updatedAt: 'desc' }, take: 6 }) : Promise.resolve([]),
    env.FEATURE_FIELD_OPERATIONS && canInspect ? db.fieldVisit.findMany({ where: { tenantId: tenant.id, status: { in: ['DRAFT', 'IN_PROGRESS', 'PAUSED', 'COMPLETED'] } }, include: { company: { select: { legalName: true, tradeName: true } }, _count: { select: { captures: true } } }, orderBy: { updatedAt: 'desc' }, take: 6 }) : Promise.resolve([]),
  ]);

  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">{env.FEATURE_V10_HOME ? 'O que deseja fazer hoje?' : 'Visão geral'}</h1><p className="mt-1 text-slate-500">{env.FEATURE_V10_HOME ? 'Comece um trabalho, importe documentos, faça uma visita ou converse com o copiloto.' : 'Operação técnica, documentos, serviços e comunicação.'}</p></div>{canCreate && <Link href="/companies/new" className="rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Nova empresa</Link>}</div>
    {env.FEATURE_V10_HOME && <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{env.FEATURE_V10_WORKS && canManageWorks && <Link href="/work-projects/new"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">NOVO</p><p className="mt-1 font-bold">Trabalho SST</p><p className="mt-1 text-xs text-slate-500">AET, PGR, PCMSO, LTCAT e outros.</p></Card></Link>}{env.FEATURE_LEGACY_IMPORTS && canManageWorks && <Link href="/legacy-imports/new"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">IMPORTAR</p><p className="mt-1 font-bold">Laudo antigo</p><p className="mt-1 text-xs text-slate-500">Cadastre e migre um acervo.</p></Card></Link>}{env.FEATURE_FIELD_OPERATIONS && canInspect && <Link href="/field-visits"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">CAMPO</p><p className="mt-1 font-bold">Iniciar visita</p><p className="mt-1 text-xs text-slate-500">Fotos, voz e medições.</p></Card></Link>}{env.FEATURE_AI_COPILOT && canManageWorks && <Link href="/copilot"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">IA</p><p className="mt-1 font-bold">Copiloto</p><p className="mt-1 text-xs text-slate-500">Diga o que precisa fazer.</p></Card></Link>}{env.FEATURE_CORPORATE_UNIVERSITY && canManageWorks && <Link href="/work-projects?serviceType=TREINAMENTO"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">CAPACITAR</p><p className="mt-1 font-bold">Treinamentos</p><p className="mt-1 text-xs text-slate-500">Cursos, avaliações e certificados.</p></Card></Link>}{env.FEATURE_OPERATIONAL_SST && canManageWorks && <Link href="/work-projects?serviceType=OPERACAO_SST"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">OPERAR</p><p className="mt-1 font-bold">SST 360</p><p className="mt-1 text-xs text-slate-500">EPI, acidentes, máquinas e conformidade.</p></Card></Link>}<Link href="/companies"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">BASE</p><p className="mt-1 font-bold">Empresas</p><p className="mt-1 text-xs text-slate-500">Estrutura e documentos.</p></Card></Link><Link href="/work-projects"><Card className="h-full hover:border-brand-300"><p className="text-xs font-semibold text-brand-700">SAÍDAS</p><p className="mt-1 font-bold">Documentos</p><p className="mt-1 text-xs text-slate-500">Revisar e emitir.</p></Card></Link></div>}
    <div className="mt-6 grid gap-4 md:grid-cols-3 xl:grid-cols-6"><StatCard label="Empresas ativas" value={companies} /><StatCard label="Campanhas ativas" value={campaigns} /><StatCard label="Documentos em revisão" value={documents} /><StatCard label="Ações abertas" value={actions} /><StatCard label="Serviços vencidos" value={servicesOverdue.length} /><StatCard label="Renovações em 30 dias" value={servicesRenewing.length} /></div>
    {(activeProjects.length > 0 || fieldVisits.length > 0) && <div className="mt-6 grid gap-6 lg:grid-cols-2">{activeProjects.length > 0 && <Card><div className="flex justify-between"><h2 className="font-bold">Continuar trabalhos</h2><Link href="/work-projects" className="text-sm text-brand-700">Ver todos</Link></div><div className="mt-3 divide-y">{activeProjects.map((project) => <Link key={project.id} href={`/work-projects/${project.id}`} className="block py-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{project.title}</p><p className="text-sm text-slate-500">{project.company.tradeName ?? project.company.legalName}</p></div><Badge tone={project.progress >= 80 ? 'success' : 'warning'}>{project.progress}%</Badge></div></Link>)}</div></Card>}{fieldVisits.length > 0 && <Card><div className="flex justify-between"><h2 className="font-bold">Coletas em campo</h2><Link href="/field-visits" className="text-sm text-brand-700">Ver todas</Link></div><div className="mt-3 divide-y">{fieldVisits.map((visit) => <Link key={visit.id} href={`/field-visits/${visit.id}`} className="flex justify-between gap-3 py-3"><div><p className="font-medium">{visit.title}</p><p className="text-sm text-slate-500">{visit.company.tradeName ?? visit.company.legalName} · {visit._count.captures} registros</p></div><Badge tone={visit.status === 'COMPLETED' ? 'success' : 'warning'}>{visit.status}</Badge></Link>)}</div></Card>}</div>}
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-bold">Serviços com prazo vencido</h2><div className="mt-3 divide-y">{servicesOverdue.map((service) => <Link key={service.id} href={`/companies/${service.companyId}/services`} className="flex items-center justify-between gap-3 py-3"><div><p className="font-medium">{service.code} · {service.name}</p><p className="text-sm text-slate-500">{service.company.tradeName ?? service.company.legalName} · prazo {formatDate(service.dueAt)}</p></div><Badge tone="danger">Vencido</Badge></Link>)}{!servicesOverdue.length && <p className="py-4 text-sm text-slate-500">Nenhum serviço vencido.</p>}</div></Card><Card><h2 className="font-bold">Renovações próximas</h2><div className="mt-3 divide-y">{servicesRenewing.map((service) => <Link key={service.id} href={`/companies/${service.companyId}/services`} className="flex items-center justify-between gap-3 py-3"><div><p className="font-medium">{service.code} · {service.name}</p><p className="text-sm text-slate-500">{service.company.tradeName ?? service.company.legalName} · renovação {formatDate(service.renewalAt)}</p></div><Badge tone="warning">Renovar</Badge></Link>)}{!servicesRenewing.length && <p className="py-4 text-sm text-slate-500">Nenhuma renovação nos próximos 30 dias.</p>}</div></Card></div>
    {canMessage && <Card className="mt-6"><div className="flex justify-between"><h2 className="font-bold">Conversas recentes</h2><Link href="/messages" className="text-sm text-brand-700">Ver todas</Link></div><div className="mt-4 divide-y">{messages.map((message) => <Link key={message.id} href={`/messages/${message.id}`} className="flex items-center justify-between py-3"><div><p className="font-medium">{message.subject}</p><p className="text-sm text-slate-500">{message.company?.tradeName ?? message.company?.legalName ?? 'Interno'}</p></div><Badge>{message.status}</Badge></Link>)}{!messages.length && <p className="py-5 text-sm text-slate-500">Nenhuma conversa pendente.</p>}</div></Card>}
  </div>;
}
