import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, Button, Card, Input, Textarea } from '@/components/ui';
import { ergonomicMethodCatalog } from '@/domain/ergonomics/catalog';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { env } from '@/lib/env';

const riskTone = (level: string): 'success' | 'warning' | 'danger' | 'neutral' => ['HIGH', 'CRITICAL'].includes(level) ? 'danger' : level === 'MODERATE' ? 'warning' : ['LOW', 'VERY_LOW'].includes(level) ? 'success' : 'neutral';
const auditTone = (status: string): 'success' | 'warning' | 'danger' | 'neutral' => status === 'PASSED' ? 'success' : status === 'PASSED_WITH_WARNINGS' ? 'warning' : 'danger';

export default async function ErgonomicsPage({ params }: { params: Promise<{ id: string }> }) {
  if (!env.FEATURE_ERGONOMICS) notFound();
  const { id } = await params;
  const { tenant } = await requireTenantPermission('ergonomics.read');
  const project = await db.workProject.findFirst({
    where: { id, tenantId: tenant.id, serviceType: { in: ['AET', 'AEP'] } },
    include: {
      company: { include: { establishments: { where: { active: true }, include: { sectors: { where: { active: true }, include: { ghes: { where: { active: true }, include: { functions: { where: { active: true } }, workstations: { where: { active: true } } } } } } } } } },
      ergonomicsProgram: { include: { demands: { orderBy: { createdAt: 'desc' } }, workSituations: { orderBy: { createdAt: 'desc' } }, participations: { orderBy: { occurredAt: 'desc' } }, assessments: { include: { workSituation: { select: { title: true } } }, orderBy: { createdAt: 'desc' } }, findings: { orderBy: [{ level: 'desc' }, { score: 'desc' }] }, preliminaryDecisions: { orderBy: { createdAt: 'desc' }, take: 5 }, audits: { orderBy: { createdAt: 'desc' }, take: 5 } } },
    },
  });
  if (!project) notFound();
  const program = project.ergonomicsProgram;
  const ghes = project.company.establishments.flatMap((est) => est.sectors.flatMap((sector) => sector.ghes.map((ghe) => ({ id: ghe.id, label: `${est.name} · ${sector.name} · ${ghe.name}`, functions: ghe.functions, workstations: ghe.workstations }))));
  if (!program) return <div><p className="text-sm font-semibold text-violet-700">AEP/AET</p><h1 className="text-3xl font-bold">{project.title}</h1><p className="mt-1 text-slate-500">Inicialize a avaliação ergonômica para estruturar demanda, atividade real, participação, métodos e plano de ação.</p><Card className="mt-6"><form action={`/api/ergonomics/${id}/bootstrap`} method="post"><Button type="submit">Inicializar AEP/AET</Button></form></Card></div>;
  const latestAudit = program.audits[0];
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-violet-700">Ergonomia · {program.stage}</p><h1 className="text-3xl font-bold">{program.title}</h1><p className="mt-1 text-slate-500">{project.company.tradeName ?? project.company.legalName} · análise centrada no trabalho real</p></div><div className="flex gap-2"><Link href={`/work-projects/${id}`} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Ver Trabalho SST</Link><form action={`/api/ergonomics/${id}/audit`} method="post"><Button type="submit">Executar auditoria</Button></form></div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-6"><Card><p className="text-xs text-slate-500">Demandas</p><p className="text-2xl font-bold">{program.demands.length}</p></Card><Card><p className="text-xs text-slate-500">Situações</p><p className="text-2xl font-bold">{program.workSituations.length}</p></Card><Card><p className="text-xs text-slate-500">Participações</p><p className="text-2xl font-bold">{program.participations.length}</p></Card><Card><p className="text-xs text-slate-500">Métodos</p><p className="text-2xl font-bold">{program.assessments.length}</p></Card><Card><p className="text-xs text-slate-500">Achados</p><p className="text-2xl font-bold">{program.findings.length}</p></Card><Card><p className="text-xs text-slate-500">Auditoria</p><p className="text-2xl font-bold">{latestAudit?.score ?? '—'}</p>{latestAudit && <Badge tone={auditTone(latestAudit.status)}>{latestAudit.status}</Badge>}</Card></div>

    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-bold">Demanda ergonômica</h2><form action={`/api/ergonomics/${id}/demands`} method="post" className="mt-4 grid gap-3"><label className="text-sm">Origem<select name="source" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="WORKER">Trabalhador</option><option value="CIPA">CIPA</option><option value="HEALTH_SURVEILLANCE">Saúde ocupacional</option><option value="PROCESS_CHANGE">Mudança de processo</option><option value="PGR">PGR</option><option value="LEGAL_REQUIREMENT">Exigência legal</option><option value="OTHER">Outra</option></select></label><label className="text-sm">Título<Input name="title" className="mt-1" required /></label><label className="text-sm">Descrição<Textarea name="description" className="mt-1" rows={4} required minLength={10} /></label><label className="text-sm">Data do gatilho<Input type="date" name="triggerDate" className="mt-1" /></label><Button type="submit">Registrar demanda</Button></form><div className="mt-4 divide-y">{program.demands.map((item)=><div className="py-3" key={item.id}><p className="text-sm font-medium">{item.title}</p><p className="text-xs text-slate-500">{item.source}</p><p className="text-xs text-slate-600">{item.description}</p></div>)}</div></Card>

    <Card><h2 className="font-bold">Participação dos trabalhadores</h2><form action={`/api/ergonomics/${id}/participation`} method="post" className="mt-4 grid gap-3"><label className="text-sm">Situação<select name="workSituationId" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Geral</option>{program.workSituations.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="text-sm">Forma<select name="kind" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="INTERVIEW">Entrevista</option><option value="OBSERVATION">Observação</option><option value="WORKSHOP">Oficina</option><option value="FOCUS_GROUP">Grupo focal</option><option value="CIPA">CIPA</option></select></label><label className="text-sm">Título<Input name="title" className="mt-1" required /></label><label className="text-sm">Participantes<Input name="participantCount" type="number" min={0} defaultValue={0} className="mt-1" /></label><label className="text-sm">Grupos<Textarea name="groups" rows={2} className="mt-1" placeholder="Um por linha" /></label><label className="text-sm">Síntese<Textarea name="summary" rows={3} className="mt-1" /></label><label className="text-sm">Resultados/encaminhamentos<Textarea name="outcomes" rows={2} className="mt-1" /></label><label className="flex gap-2 text-sm"><input type="checkbox" name="confidential" /> Conteúdo confidencial</label><Button type="submit">Registrar participação</Button></form></Card></div>

    <Card className="mt-6"><h2 className="font-bold">Situações de trabalho e análise da atividade</h2><p className="mt-1 text-sm text-slate-500">Compare trabalho prescrito e real, variabilidades, estratégias, organização, exigências e condições ambientais.</p><form action={`/api/ergonomics/${id}/situations`} method="post" className="mt-4 grid gap-3 lg:grid-cols-3"><label className="text-sm lg:col-span-2">Título<Input name="title" className="mt-1" required /></label><label className="text-sm">GHE<select name="gheId" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Sem vínculo</option>{ghes.map((ghe)=><option key={ghe.id} value={ghe.id}>{ghe.label}</option>)}</select></label><label className="text-sm">Trabalho prescrito<Textarea name="prescribedWork" className="mt-1" rows={4} /></label><label className="text-sm">Trabalho real<Textarea name="actualWork" className="mt-1" rows={4} /></label><label className="text-sm">Atividades<Textarea name="activities" className="mt-1" rows={4} placeholder="Uma por linha" /></label><label className="text-sm">Variabilidades<Textarea name="variability" className="mt-1" rows={3} /></label><label className="text-sm">Estratégias e regulações<Textarea name="strategies" className="mt-1" rows={3} /></label><label className="text-sm">Restrições e constrangimentos<Textarea name="constraints" className="mt-1" rows={3} /></label><label className="text-sm">Organização do trabalho<Textarea name="workOrganization" className="mt-1" rows={3} /></label><label className="text-sm">Exigências cognitivas<Textarea name="cognitiveDemands" className="mt-1" rows={3} /></label><label className="text-sm">Fatores psicossociais<Textarea name="psychosocialFactors" className="mt-1" rows={3} /></label><label className="text-sm">Condições ambientais<Textarea name="environmentalConditions" className="mt-1" rows={3} /></label><label className="text-sm">População e jornada<Textarea name="population" className="mt-1" rows={3} /></label><label className="text-sm">Pausas<Input name="breaks" className="mt-1" /></label><label className="text-sm">Duração da tarefa (min)<Input name="taskDurationMinutes" type="number" min={0} className="mt-1" /></label><label className="text-sm">Ciclos por hora<Input name="cyclesPerHour" type="number" min={0} step="0.1" className="mt-1" /></label><div className="flex items-end"><Button type="submit" className="w-full">Salvar situação</Button></div></form><div className="mt-5 divide-y">{program.workSituations.map((item)=><div key={item.id} className="py-3"><p className="font-medium">{item.title}</p><p className="text-xs text-slate-500">Prescrito: {item.prescribedWork ? 'registrado' : 'pendente'} · Real: {item.actualWork ? 'registrado' : 'pendente'}</p></div>)}</div></Card>

    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-bold">Métodos ergonômicos</h2><p className="mt-1 text-sm text-slate-500">RULA, REBA e NIOSH são calculados pelo código. Outros métodos ficam em revisão técnica até motor validado.</p><form action={`/api/ergonomics/${id}/assessments`} method="post" className="mt-4 grid gap-3"><label className="text-sm">Situação<select name="workSituationId" required className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Selecione</option>{program.workSituations.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="text-sm">Método<select name="method" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5">{ergonomicMethodCatalog.map((m)=><option key={m.code} value={m.code}>{m.name}{m.engineAvailable ? ' · motor disponível' : ' · revisão manual'}</option>)}</select></label><label className="text-sm">Justificativa de aplicabilidade<Textarea name="applicability" required minLength={10} rows={3} className="mt-1" /></label><label className="text-sm">Entradas em JSON<Textarea name="inputs" required rows={5} className="mt-1 font-mono text-xs" defaultValue={'{"upperArm":1,"lowerArm":1,"wrist":1,"wristTwist":1,"neck":1,"trunk":1,"legs":1}'} /></label><label className="text-sm">Pontuação manual<Input name="manualScore" type="number" step="0.01" className="mt-1" /></label><label className="text-sm">Classificação manual<Input name="manualClassification" className="mt-1" /></label><Button type="submit">Calcular ou registrar</Button></form><div className="mt-4 divide-y">{program.assessments.map((item)=><div key={item.id} className="py-3"><div className="flex justify-between gap-2"><div><p className="text-sm font-medium">{item.method} · {item.workSituation.title}</p><p className="text-xs text-slate-500">{item.score ?? '—'} · {item.classification ?? 'aguardando resultado'} · {item.engineVersion ?? 'manual'}</p></div><Badge tone={item.status==='APPROVED'?'success':item.status==='REJECTED'?'danger':'warning'}>{item.status}</Badge></div>{!['APPROVED','REJECTED'].includes(item.status)&&<form className="mt-2 flex gap-2" action={`/api/ergonomics/${id}/assessments/${item.id}/review`} method="post"><Button type="submit" name="decision" value="approve" variant="outline" className="px-3 py-1.5 text-xs">Aprovar</Button><Button type="submit" name="decision" value="reject" variant="ghost" className="px-3 py-1.5 text-xs">Rejeitar</Button></form>}</div>)}</div></Card>

    <Card><div className="flex items-center justify-between"><div><h2 className="font-bold">Achados e diagnóstico</h2><p className="text-sm text-slate-500">Integra automaticamente o achado ao cadastro canônico de riscos.</p></div><form action={`/api/ergonomics/${id}/action-plan`} method="post"><Button type="submit" variant="secondary">Gerar plano</Button></form></div><form action={`/api/ergonomics/${id}/findings`} method="post" className="mt-4 grid gap-3"><label className="text-sm">Situação<select name="workSituationId" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Geral</option>{program.workSituations.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="text-sm">Dimensão<select name="dimension" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="PHYSICAL">Física</option><option value="COGNITIVE">Cognitiva</option><option value="ORGANIZATIONAL">Organizacional</option><option value="PSYCHOSOCIAL">Psicossocial</option><option value="ENVIRONMENTAL">Ambiental</option><option value="ACCESSIBILITY">Acessibilidade</option></select></label><label className="text-sm">Código<Input name="code" required className="mt-1" placeholder="ERG-001" /></label><label className="text-sm">Título<Input name="title" required className="mt-1" /></label><label className="text-sm">Descrição<Textarea name="description" required minLength={10} rows={3} className="mt-1" /></label><label className="text-sm">Recomendação<Textarea name="recommendation" rows={3} className="mt-1" /></label><div className="grid grid-cols-3 gap-2"><label className="text-xs">Severidade<Input name="severity" type="number" min={1} max={5} defaultValue={1} /></label><label className="text-xs">Probabilidade<Input name="probability" type="number" min={1} max={5} defaultValue={1} /></label><label className="text-xs">Exposição<Input name="exposure" type="number" min={1} max={5} defaultValue={1} /></label></div><Button type="submit">Salvar achado</Button></form><div className="mt-4 divide-y">{program.findings.map((item)=><div key={item.id} className="py-3"><div className="flex justify-between"><div><p className="text-sm font-medium">{item.code} · {item.title}</p><p className="text-xs text-slate-500">{item.dimension} · {item.recommendation ?? 'sem recomendação'}</p></div><Badge tone={riskTone(item.level)}>{item.level} · {item.score}</Badge></div></div>)}</div></Card></div>

    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-bold">Decisão da AEP</h2><p className="mt-1 text-sm text-slate-500">Aprofundamento para AET deve ser justificado e aprovado pelo responsável.</p><form action={`/api/ergonomics/${id}/aep-decision`} method="post" className="mt-4 grid gap-3"><label className="text-sm">Conclusão<select name="conclusion" className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="NO_FURTHER_ACTION">Sem aprofundamento no escopo</option><option value="IMPROVEMENT_ACTIONS">Medidas de melhoria</option><option value="AET_REQUIRED">AET necessária</option><option value="INCONCLUSIVE">Inconclusiva</option></select></label><label className="flex gap-2 text-sm"><input type="checkbox" name="requiresAet" /> Habilitar etapa AET</label><label className="text-sm">Fundamentação<Textarea name="rationale" required minLength={20} rows={4} className="mt-1" /></label><input type="hidden" name="status" value="APPROVED" /><Button type="submit">Aprovar decisão</Button></form><div className="mt-4 divide-y">{program.preliminaryDecisions.map((item)=><div key={item.id} className="py-3"><p className="text-sm font-medium">{item.conclusion}</p><p className="text-xs text-slate-500">AET: {item.requiresAet?'sim':'não'} · {item.status}</p><p className="text-xs text-slate-600">{item.rationale}</p></div>)}</div></Card><Card><h2 className="font-bold">Auditorias técnicas</h2><div className="mt-3 divide-y">{program.audits.map((run)=><div key={run.id} className="py-3"><div className="flex justify-between"><p className="text-sm font-medium">{run.createdAt.toLocaleString('pt-BR')}</p><div className="flex gap-2"><strong>{run.score}/100</strong><Badge tone={auditTone(run.status)}>{run.status}</Badge></div></div>{Array.isArray(run.findings)&&run.findings.slice(0,8).map((f,index)=>{const item=f as {severity?:string;message?:string};return <p className="mt-1 text-xs text-slate-600" key={index}>{item.severity==='ERROR'?'✗':item.severity==='WARNING'?'⚠':'•'} {item.message}</p>})}</div>)}{!program.audits.length&&<p className="text-sm text-slate-500">Nenhuma auditoria executada.</p>}</div></Card></div>
  </div>;
}
