import Link from 'next/link';
import { notFound } from 'next/navigation';
import { env } from '@/lib/env';
import { publicTrainingEnrollment } from '@/lib/training';

const tone = (status: string) => status === 'PASSED' || status === 'COMPLETED' || status === 'ISSUED' ? 'text-emerald-700 bg-emerald-50' : status === 'FAILED' || status === 'REVOKED' ? 'text-red-700 bg-red-50' : 'text-amber-700 bg-amber-50';
const contentText = (content: unknown) => {
  if (!content || typeof content !== 'object') return '';
  const value = content as Record<string, unknown>;
  return [value.text, value.summary, value.instructions].filter((item): item is string => typeof item === 'string' && item.trim().length > 0).join('\n\n');
};

export default async function LearnerTrainingPage({ params }: { params: Promise<{ token: string }> }) {
  if (!env.FEATURE_CORPORATE_UNIVERSITY) notFound();
  const { token } = await params; const enrollment = await publicTrainingEnrollment(token); if (!enrollment) notFound();
  const completedLessons = new Set(enrollment.lessonProgress.filter((item) => item.status === 'COMPLETED').map((item) => item.lessonId));
  const latestAttempt = new Map<string, (typeof enrollment.attempts)[number]>();
  for (const attempt of enrollment.attempts) if (!latestAttempt.has(attempt.assessmentId)) latestAttempt.set(attempt.assessmentId, attempt);
  return <main className="mx-auto max-w-4xl px-4 py-8 sm:px-6">
    <header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-brand-700">Universidade Corporativa</p><h1 className="mt-1 text-3xl font-bold">{enrollment.course.title}</h1><p className="mt-2 text-slate-600">{enrollment.worker.fullName} · {enrollment.company.tradeName ?? enrollment.company.legalName}</p><div className="mt-4 flex flex-wrap items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${tone(enrollment.status)}`}>{enrollment.status}</span><span className="text-sm text-slate-600">Progresso: {enrollment.progress}%</span>{enrollment.dueAt&&<span className="text-sm text-slate-600">Prazo: {enrollment.dueAt.toLocaleDateString('pt-BR')}</span>}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-brand-600" style={{width:`${Math.min(100,Math.max(0,enrollment.progress))}%`}} /></div></header>

    <section className="mt-6 space-y-5">{enrollment.course.modules.map((module) => <article key={module.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{module.title}</h2>{module.description&&<p className="mt-1 text-sm text-slate-600">{module.description}</p>}<div className="mt-4 space-y-4">{module.lessons.map((lesson) => { const done=completedLessons.has(lesson.id); const text=contentText(lesson.content); return <div key={lesson.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{lesson.title}</p><p className="text-xs text-slate-500">{lesson.kind} · {lesson.estimatedMinutes} min{lesson.mandatory?' · obrigatória':''}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${done?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{done?'Concluída':'Pendente'}</span></div>{lesson.description&&<p className="mt-3 text-sm text-slate-700">{lesson.description}</p>}{text&&<p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm text-slate-600">{text}</p>}<div className="mt-3"><Link href={`/learn/${token}/lessons/${lesson.id}`} className="inline-block rounded-xl bg-brand-600 px-3 py-2 text-sm font-semibold text-white">{done?'Revisar aula':'Abrir aula'}</Link></div></div>})}</div></article>)}</section>

    <section className="mt-6 space-y-5">{enrollment.course.assessments.map((assessment) => { const attempt=latestAttempt.get(assessment.id); return <article key={assessment.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="text-xl font-bold">{assessment.title}</h2><p className="text-sm text-slate-500">Nota mínima: {Number(assessment.passingScore)} · até {assessment.maxAttempts} tentativa(s)</p></div>{attempt&&<span className={`rounded-full px-3 py-1 text-xs font-bold ${tone(attempt.status)}`}>{attempt.status}{attempt.score!=null?` · ${Number(attempt.score)}`:''}</span>}</div>{attempt?.status==='PASSED'?<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Avaliação aprovada.</p>:<form action={`/api/public/training/${token}/assessments/${assessment.id}`} method="post" className="mt-5 space-y-5">{assessment.questions.map((question,index)=><fieldset key={question.id} className="rounded-xl border border-slate-200 p-4"><legend className="px-1 text-sm font-semibold">{index+1}. {question.prompt}</legend>{question.type==='SHORT_TEXT'?<textarea name={`q_${question.id}`} rows={4} required className="mt-3 w-full rounded-xl border border-slate-300 p-3"/>:<div className="mt-3 space-y-2">{(Array.isArray(question.options)?question.options:question.type==='TRUE_FALSE'?['true','false']:[]).map((option)=><label key={String(option)} className="flex items-center gap-2 text-sm"><input type={question.type==='MULTIPLE_CHOICE'?'checkbox':'radio'} name={`q_${question.id}`} value={String(option)} required={question.type!=='MULTIPLE_CHOICE'}/><span>{question.type==='TRUE_FALSE'?(String(option)==='true'?'Verdadeiro':'Falso'):String(option)}</span></label>)}</div>}</fieldset>)}<button type="submit" className="rounded-xl bg-brand-600 px-4 py-2.5 font-semibold text-white">Enviar avaliação</button></form>}</article>})}</section>

    {enrollment.course.requiresPractical&&<section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">Etapa prática</h2><p className="mt-1 text-sm text-amber-800">Este curso exige avaliação prática por instrutor autorizado. O certificado somente será liberado após a aprovação.</p></section>}
    {enrollment.certificate?.status==='ISSUED'&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="font-bold text-emerald-900">Certificado disponível</h2><p className="mt-1 text-sm text-emerald-800">Código: {enrollment.certificate.code}</p><Link href={`/certificates/${enrollment.certificate.verificationHash}`} className="mt-3 inline-block rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Validar certificado</Link></section>}
  </main>;
}
