export type OperationalAuditFinding = { code: string; severity: 'ERROR' | 'WARNING'; message: string };
export type OperationalAuditInput = {
  hasScope: boolean;
  hasResponsible: boolean;
  ppeItems: number;
  expiredCaItems: number;
  lowStockItems: number;
  incidentsOpen: number;
  incidentsWithoutInvestigation: number;
  catPending: number;
  permitsActive: number;
  permitsExpiredOpen: number;
  machines: number;
  blockedMachines: number;
  overdueMachineInspections: number;
  chemicalProducts: number;
  chemicalsWithoutSds: number;
  emergencyPlanApproved: boolean;
  drillsOverdue: number;
  cipaRequired: boolean;
  cipaActive: boolean;
  contractors: number;
  nonCompliantContractors: number;
  obligations: number;
  overdueObligations: number;
  esocialRejected: number;
  workflowProgress: number;
};

export function auditOperationalCompleteness(input: OperationalAuditInput) {
  const findings: OperationalAuditFinding[] = [];
  const error = (code: string, message: string) => findings.push({ code, severity: 'ERROR' as const, message });
  const warning = (code: string, message: string) => findings.push({ code, severity: 'WARNING' as const, message });
  if (!input.hasScope) error('OPS_SCOPE', 'Escopo do programa operacional não foi definido.');
  if (!input.hasResponsible) error('OPS_RESPONSIBLE', 'Responsável pelo programa operacional não foi definido.');
  if (input.ppeItems < 1) warning('OPS_PPE_CATALOG', 'Catálogo de EPI ainda está vazio.');
  if (input.expiredCaItems > 0) error('OPS_PPE_CA', `${input.expiredCaItems} item(ns) de EPI possuem CA vencido.`);
  if (input.lowStockItems > 0) warning('OPS_PPE_STOCK', `${input.lowStockItems} item(ns) atingiram o estoque mínimo.`);
  if (input.incidentsOpen > 0) warning('OPS_INCIDENT_OPEN', `${input.incidentsOpen} ocorrência(s) permanecem abertas.`);
  if (input.incidentsWithoutInvestigation > 0) error('OPS_INCIDENT_INVESTIGATION', `${input.incidentsWithoutInvestigation} ocorrência(s) críticas exigem investigação formal.`);
  if (input.catPending > 0) error('OPS_CAT_PENDING', `${input.catPending} CAT(s) obrigatória(s) ainda não foram registradas.`);
  if (input.permitsExpiredOpen > 0) error('OPS_PERMIT_EXPIRED', `${input.permitsExpiredOpen} permissão(ões) vencida(s) continuam abertas.`);
  if (input.machines < 1) warning('OPS_MACHINE_INVENTORY', 'Inventário de máquinas ainda está vazio.');
  if (input.blockedMachines > 0) warning('OPS_MACHINE_BLOCKED', `${input.blockedMachines} máquina(s) estão bloqueadas ou restritas.`);
  if (input.overdueMachineInspections > 0) error('OPS_MACHINE_INSPECTION', `${input.overdueMachineInspections} inspeção(ões) de máquinas estão vencidas.`);
  if (input.chemicalProducts < 1) warning('OPS_CHEMICAL_INVENTORY', 'Inventário de produtos químicos ainda está vazio.');
  if (input.chemicalsWithoutSds > 0) error('OPS_CHEMICAL_SDS', `${input.chemicalsWithoutSds} produto(s) químico(s) não possuem FDS vinculada.`);
  if (!input.emergencyPlanApproved) error('OPS_EMERGENCY_PLAN', 'Plano de emergência aprovado não foi registrado.');
  if (input.drillsOverdue > 0) warning('OPS_DRILL_OVERDUE', `${input.drillsOverdue} simulado(s) estão pendentes ou vencidos.`);
  if (input.cipaRequired && !input.cipaActive) error('OPS_CIPA', 'CIPA obrigatória sem ciclo ativo.');
  if (input.nonCompliantContractors > 0) error('OPS_CONTRACTOR', `${input.nonCompliantContractors} contratada(s) estão não conformes ou bloqueadas.`);
  if (input.obligations < 1) warning('OPS_LEGAL_MATRIX', 'Matriz de requisitos legais ainda está vazia.');
  if (input.overdueObligations > 0) error('OPS_LEGAL_OVERDUE', `${input.overdueObligations} obrigação(ões) estão vencidas.`);
  if (input.esocialRejected > 0) error('OPS_ESOCIAL_REJECTED', `${input.esocialRejected} evento(s) do eSocial foram rejeitados.`);
  if (input.workflowProgress < 100) warning('OPS_WORKFLOW', `Workflow está em ${input.workflowProgress}% de conclusão.`);
  const errors = findings.filter((item) => item.severity === 'ERROR').length;
  const warnings = findings.length - errors;
  const score = Math.max(0, 100 - errors * 9 - warnings * 3);
  return { status: errors ? 'FAILED' as const : warnings ? 'PASSED_WITH_WARNINGS' as const : 'PASSED' as const, score, findings };
}
