import { notFound } from 'next/navigation';
import { Badge, Button, Card, Input, Textarea } from '@/components/ui';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { env } from '@/lib/env';
import { tenantBillingOverview } from '@/lib/billing';

const tone=(status:string):'success'|'warning'|'danger'|'neutral'=>['ACTIVE','PAID'].includes(status)?'success':['PAST_DUE','OVERDUE','SUSPENDED'].includes(status)?'danger':['TRIAL','OPEN'].includes(status)?'warning':'neutral';
export default async function BillingPage(){if(!env.FEATURE_BILLING)notFound();const{tenant}=await requireTenantPermission('billing.read');const [plans,overview]=await Promise.all([db.saasPlan.findMany({where:{active:true},orderBy:{priceCents:'asc'}}),tenantBillingOverview(tenant.id)]);return <div><div><p className="text-sm font-semibold text-fuchsia-700">Comercial</p><h1 className="text-3xl font-bold">Planos, cobrança e uso</h1><p className="mt-1 text-slate-500">Assinaturas, faturas, franquias e preparação para gateways de pagamento.</p></div><div className="mt-6 grid gap-4 md:grid-cols-3"><Card><p className="text-xs text-slate-500">Assinatura</p><p className="text-2xl font-bold">{overview.plan?.name??'Sem plano'}</p>{overview.state!=='NONE'&&<Badge tone={tone(String(overview.state))}>{String(overview.state)}</Badge>}</Card><Card><p className="text-xs text-slate-500">Período atual</p><p className="text-lg font-bold">{overview.subscription?`${overview.subscription.currentPeriodStart.toISOString().slice(0,10)} → ${overview.subscription.currentPeriodEnd.toISOString().slice(0,10)}`:'—'}</p></Card><Card><p className="text-xs text-slate-500">Faturas abertas</p><p className="text-2xl font-bold">{overview.invoices.filter(i=>['OPEN','OVERDUE'].includes(i.status)).length}</p></Card></div>
<div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-bold">Criar plano SaaS</h2><form action="/api/billing/plans" method="post" className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-2"><Input name="code" placeholder="Código" required/><Input name="name" placeholder="Nome" required/></div><Textarea name="description" placeholder="Descrição" rows={2}/><div className="grid gap-3 md:grid-cols-3"><select name="interval" className="rounded-xl border px-3 py-2.5"><option value="MONTHLY">Mensal</option><option value="YEARLY">Anual</option><option value="ONE_TIME">Único</option></select><Input name="priceCents" type="number" min={0} placeholder="Preço em centavos" required/><Input name="trialDays" type="number" min={0} defaultValue={0} placeholder="Teste"/></div><Textarea name="features" rows={3} placeholder="Recursos, um por linha"/><Textarea name="limits" rows={4} defaultValue={'{"activeCompanies":30,"activeUsers":5,"aiRequests":1000,"storageBytes":10737418240}'} className="font-mono"/><Button type="submit">Criar plano</Button></form></Card><Card><h2 className="font-bold">Ativar assinatura</h2><form action="/api/billing/subscriptions" method="post" className="mt-4 grid gap-3"><select name="planId" required className="rounded-xl border px-3 py-2.5"><option value="">Selecione</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {(p.priceCents/100).toLocaleString('pt-BR',{style:'currency',currency:p.currency})}/{p.interval}</option>)}</select><select name="provider" className="rounded-xl border px-3 py-2.5"><option value="MANUAL">Manual</option><option value="ASAAS">Asaas</option><option value="MERCADO_PAGO">Mercado Pago</option></select><Button type="submit">Ativar assinatura</Button></form><h3 className="mt-6 font-semibold">Gerar fatura</h3><form action="/api/billing/invoices" method="post" className="mt-3 grid gap-3"><Input type="hidden" name="subscriptionId" value={overview.subscription?.id??''}/><Input name="description" placeholder="Descrição" required/><div className="grid gap-3 md:grid-cols-2"><Input name="amountCents" type="number" min={0} placeholder="Valor em centavos" required/><Input name="dueAt" type="date" required/></div><Button type="submit">Criar fatura</Button></form></Card></div>
<Card className="mt-6"><h2 className="font-bold">Faturas recentes</h2><div className="mt-3 divide-y">{overview.invoices.map(i=><div key={i.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><p className="text-sm font-medium">{i.description}</p><p className="text-xs text-slate-500">{(i.amountCents/100).toLocaleString('pt-BR',{style:'currency',currency:i.currency})} · vence {i.dueAt.toISOString().slice(0,10)} · {i.provider}</p></div><div className="flex items-center gap-2"><Badge tone={tone(i.status)}>{i.status}</Badge>{i.status==='OPEN'&&<form action={`/api/billing/invoices/${i.id}/transition`} method="post"><Button name="status" value="PAID" type="submit">Marcar paga</Button></form>}</div></div>)}</div></Card></div>}
